blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),  # создание поста в blogpost_form
    path('', BlogListView.as_view(), name='list'),  # список постов в blogpost_list
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),  # детали одного поста в blogpost_detail
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),  # редактирование поста
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),  # подтверждение и удаление
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='dogs')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView,  VerifyEmailView, \
    VerifyEmailSentView, EmailConfirmedView, UserPasswordResetView, UserPasswordResetConfirmView, \
    UserPasswordResetDoneView, UserPasswordResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_email/<str:uidb64>/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('verify_email_sent/', VerifyEmailSentView.as_view(), name='verify_email_sent'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('password/reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<str:uidb64>/<str:token>/', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete')
    ]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    # email_verify = models.BooleanField(default=False, verbose_name='верификация')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import EmailField

from main.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        # fields = ('email', 'password1', 'password2')
        fields = ('email',)
        field_classes = {'email':EmailField}


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'avatar', 'phone', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.apps import config
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from users.utils import send_verification_email


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        send_verification_email(new_user)
        return redirect('users:verify_email_sent')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class VerifyEmailView(View):
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = uidb64
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        return user


class VerifyEmailSentView(View):
    def get(self, request):
        return render(request, 'users/verify_email_sent.html')


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'


class UserPasswordResetView(PasswordResetView):
    email_template_name = 'users/registration/password_reset_email.html'
    template_name = 'users/registration/password_reset_form.html'
    success_url = reverse_lazy('users:password_reset_done')


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/registration/password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/registration/password_reset_confirm.html'
    success_url = reverse_lazy("users:password_reset_complete")


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/registration/password_reset_complete.html'

users/templates/users/email_confirmed.html
{% extends 'main/base.html' %}
{% block content %}
    <h3>
        Ваш адрес электронной почты подтвержден! Аккаунт активирован!
    </h3>

{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="buttonbtn btn-outline-success">Войти</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                    <div class="card-body">
                        {{ form.as_p }}
                        <button type="submit" class="button btn btn-outline-success">Регистрация</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Профиль
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="buttonbtn btn-outline-success">Сохранить</button>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger" >Сгенерировать пароль</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/verify_email.html
Здравствуйте!
Ваш аккаунт: {{ email }}.

Пожалуйста, перейдите по ссылке, чтобы закончить регистрацию:
{{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}

users/templates/users/verify_email_sent.html
{% extends 'main/base.html' %}

{% block content %}
  <div style="display: flex; flex-direction: column; align-items: center;">
    <h2>Спасибо за регистрацию!</h2>
    <p>Пожалуйста, проверьте свою электронную почту, чтобы подтвердить свою учетную запись.</p>
  </div>
{% endblock %}