blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),  # создание поста в blogpost_form
    path('', BlogListView.as_view(), name='list'),  # список постов в blogpost_list
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),  # детали одного поста в blogpost_detail
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),  # редактирование поста
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),  # подтверждение и удаление
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='dogs')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import ProductsListView, CategoryListView, OneProductDetailView, ProductCreateView, \
    OneProductUpdateView, OneProductDeleteView

app_name = MainConfig.name



urlpatterns = [
    path('', ProductsListView.as_view(), name='index_list'),
    path('categories/', CategoryListView.as_view(), name='categories_list'),
    path('<int:pk>/product/', OneProductDetailView.as_view(), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>', OneProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>', OneProductDeleteView.as_view(), name='product_delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView,  VerifyEmailView, \
    VerifyEmailSentView, EmailConfirmedView, UserPasswordResetView, UserPasswordResetConfirmView, \
    UserPasswordResetDoneView, UserPasswordResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_email/<str:uidb64>/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('verify_email_sent/', VerifyEmailSentView.as_view(), name='verify_email_sent'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('password/reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<str:uidb64>/<str:token>/', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete')
    ]

main/models.py
from django.db import models
from users.models import User


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='категория')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'  # Настройка для наименования одного объекта
        verbose_name_plural = 'категории'  # Настройка для наименования набора объектов
        ordering = ('name',)  # Сортировка по имени


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    picture = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='создан', **NULLABLE)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='изменен', **NULLABLE)
    price = models.FloatField(verbose_name='цена')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} ({self.price})'


    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты '

class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=350, verbose_name='название версии')

    active_version = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.product} - {self.version_name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

main/forms.py
from django import forms

from main.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('owner',)

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']  # список запрещенных слов
        for word in forbidden_words:
            # Проверяем, содержит ли название или описание запрещенное слово
            if word in name.lower() or word in description.lower():
                # Если содержит, генерируем исключение с сообщением об ошибке
                raise forms.ValidationError(f'Слово "{word}" запрещено в названии и описании продукта.')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

main/views.py
from django.contrib.auth import mixins
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main.forms import ProductForm, VersionForm
from main.models import Category, Product, Version


# Create your views here.

class ProductsListView(mixins.LoginRequiredMixin, ListView):
    """Контроллер страницы со всеми товарами"""
    model = Product
    template_name = 'main/index_list.html'
    context_object_name = 'object_list'
    extra_context = {
        'title': 'Товары'
    }
def index(request):
    """Контроллер страницы со всеми товарами"""
    context = {
        'object_list': Product.objects.all(),
        'title': 'Товары'
    }
    return render(request, 'main/index_list.html', context)

def categories(request):
    """Контроллер страницы со списком категорий"""
    context = {
        'object_list': Category.objects.all(),
        'title': 'Категории'
    }
    return render(request, 'main/categories_list.html', context)

class CategoryListView(ListView):
    """Контроллер страницы со списком категорий"""
    model = Category
    template_name = 'main/categories_list.html'
    context_object_name = 'categories_list'
    extra_context = {
        'title': 'Категории товаров'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.all()
        return context_data


class OneProductDetailView(DetailView):
    model = Product
    template_name = 'main/product_detail.html'
    context_object_name = 'object'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = Product.objects.filter(id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['product_pk'] = product_item.pk,
        context_data['title'] = f'  {product_item.name}'

        return context_data


class ProductCreateView(mixins.LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("main:index_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class OneProductUpdateView(mixins.LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("main:index_list")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.owner != self.request.user:
            raise Http404("Вы не являетесь владельцем продукта.")
        return obj

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(self.model, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()

        return super().form_valid(form)


class OneProductDeleteView(mixins.LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("main:index_list")

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Магазин женской одежды</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">Магазин</h4>
              <p class="text-muted">это магазины, специализирующиеся на женской одежде и аксессуарах. В своем большинстве все вещи представляют молодежную моду.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Меню</h4>
              <ul class="list-unstyled">
                <li><a href="{% url 'main:index_list' %}" class="text-white">Все товары</a></li>
                <li><a href="{% url 'main:categories_list' %}" class="text-white">Категории</a></li>
                {% if user.is_authenticated %}
                      <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                      <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                {% else %}
                      <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                      <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>каталог</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{title}}</h1>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
        {% block content %}
        {% endblock %}

        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

main/templates/main/categories.html
{% extends 'main/base.html' %}

{% block content %}

  <div class="row">
    {% for object in object_list %}
            {% include 'main/includes/inc_categories.html' %}
    {% endfor %}
          </div>
{%endblock%}

main/templates/main/categories_list.html
{% extends 'main/base.html' %}

{% block content %}

  <div class="row">
    {% for object in object_list %}
            {% include 'main/includes/inc_categories.html' %}
    {% endfor %}
          </div>
{%endblock%}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

  <div class="row">
    {% for object in object_list %}
            {% include 'main/includes/inc_products.html' with object=object %}
    {% endfor %}
          </div>
{%endblock%}

main/templates/main/index_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
            {% if user.is_authenticated %}
                <a href="{% url 'main:product_create' %}" class="btn btn-primary m-2">Добавить продукт</a>
            {% endif  %}
    </div>
    <div class="row">
        {% for object in object_list %}
            {% include 'main/includes/inc_products.html' with object=object %}
        {% endfor %}
    </div>
{%endblock%}

main/templates/main/product.html
{% extends 'main/base.html' %}
{% load my_tag %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-14">
                <h5>{{ object.name }}</h5>
                <p>Цена: {{ object.price }}</p>
                <p>{{ object.description }}</p>
                    <img class="img-fluid"
                        src="{{ object.picture|mymedia}}"
                        alt="Product image">
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                               <p>Хотите удалить продукт "{{ object.name }}"</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'main:index_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}
{% load my_tag %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-14">
                <h5>{{ object.name }}</h5>
                <p>Цена: {{ object.price }}</p>
                <p>{{ object.description }}</p>
                    <img class="img-fluid"
                        src="{{ object.picture|mymedia}}"
                        alt="Product image">
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Добавить инструмент
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="buttonbtn btn-outline-success">Сохранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        Добавить версию
                    </h4>
                </div>
                <div class="card-body">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% endfor %}
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
    </form>
</div>
{% endblock %}